let content = document.querySelector('.js-generated.content')

let header = document.createElement('h1')
    header.setAttribute('class', 'dog-name')
    header.append('Rizzo')
content.append(header)

let mainDiv = document.createElement('div')
    mainDiv.setAttribute('class', 'dog-content')
        let dogImage = document.createElement('img')
        dogImage.src = './assets/rizzo.jpg'
        dogImage.setAttribute('class', 'dog-image')
    mainDiv.append(dogImage)

    let dogDetails = document.createElement('div')
        dogDetails.setAttribute('class', 'dog-details')
            let descriptionTitle = document.createElement('h3')
                descriptionTitle.append('Description:')
        dogDetails.append(descriptionTitle)
             let description = document.createElement('p')
                description.append('This gentle dog is aloof toward her owner, and never comes when called. She always acts as though any stranger she meets will harm her, and dislikes other animals.')
        dogDetails.append(description)
            let feedingTimesTitle = document.createElement('h3')
                feedingTimesTitle.append('Feeding Times:')
        dogDetails.append(feedingTimesTitle)
            let feedingTimes = document.createElement('ul')
                let firstFeeding = document.createElement('li')
                    firstFeeding.append('9:00 am')
                let secondFeeding = document.createElement('li')
                    secondFeeding.append('12:00 pm')
                let thirdFeeding = document.createElement('li')
                    thirdFeeding.append('5:00 pm')
                feedingTimes.append(firstFeeding, secondFeeding, thirdFeeding)
        dogDetails.append(feedingTimes)
    mainDiv.append(dogDetails)
content.append(mainDiv)